trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: publishArtifacts
    displayName: 'Publish Build Artifacts'
    type: boolean
    default: true
  - name: buildConfiguration
    displayName: 'Build Configuration'
    type: string
    default: 'Release'
    values:
      - 'Release'
      - 'Debug'
  - name: pipelineDebug
    displayName: Pipeline Debug
    type: boolean
    default: false

variables:
  projectName: 'netcore-todos'
  System.Debug: ${{ parameters.pipelineDebug }}

name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

resources:
  repositories:
    - repository: templates
      name: common\yaml-templates
      type: git
      ref: main

stages:
  - stage: main
    displayName: Main Stage
    
    jobs:

      - job: Build_Test
        displayName: Build and Test

        steps:
          - checkout: self
            clean: true

          - template: dotnet-build-test.template.yml@templates
            parameters:
              projectName: ${{ variables.projectName }}
              buildConfiguration: ${{ parameters.buildConfiguration }}
              # Only publish if it's NOT a PR, and we want to publish
              publishArtifacts: ${{ and(ne(variables['Build.Reason'], 'PullRequest'), eq(parameters.publishArtifacts, true)) }}
              coverageThreshold: 70