trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: buildConfiguration
    displayName: 'Build Configuration'
    type: string
    default: 'Release'
    values:
      - 'Release'
      - 'Debug'

variables:
  projectName: 'netcore-todos'

name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

resources:
  repositories:
    - repository: templates
      name: common\yaml-templates
      type: git
      ref: main

extends:
  template: dotnet-full-build-test.template.yml@templates
  parameters:
    projectName: ${{ variables.projectName }}
    diffCoverageOnly: true
    publishArtifacts: false
    buildConfiguration: ${{ parameters.buildConfiguration }}